export { default as Dashboard} from './Dashboard';
export { default as Kanban } from './Kanban';
export { default as Orders } from './Orders';
export { default as Team} from './Team';
export { default as Customers } from './Customers';
export { default as Calendar } from './Calendar';
export { default as Area } from './Charts/Area';
export { default as Bar } from './Charts/Bar';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Stacked } from './Charts/Stacked';